while ($true) {
$networkFolder = "\\nova\Public\user10216\3D-Print-  Mashin"
$allowedExtensions = @(".stl", ".obj", ".gcode")
$usbDriveLetter = "D:"
$today = (Get-Date).ToString("yyyy-MM-dd")

function a {
    $b = Get-WmiObject -Query "SELECT * FROM Win32_LogicalDisk WHERE DeviceID = '$usbDriveLetter'"
    if ($b) { return $b.DeviceID } else { Write-Host "USB drive with letter '$usbDriveLetter' not found."; return $null }
}

function b {
    param([string]$c)
    $d = [System.IO.Path]::GetExtension($c).ToLower()
    if ($d -eq ".stl") {
        $e = Get-Content -Path $c -TotalCount 5
        if ($e -match "^solid") { return $true }
    } elseif ($d -eq ".obj") {
        $e = Get-Content -Path $c -TotalCount 5
        if ($e -match "^#") { return $true }
    } elseif ($d -eq ".gcode") {
        $e = Get-Content -Path $c -TotalCount 10
        if ($e -match "^(; generated by PrusaSlicer|; G-Code generated by Simplify3D)") { return $true }
    }
    return $false
}

function c {
    param ($f)
    $g = $true
    $h = Get-ChildItem -Path $f -File
    foreach ($i in $h) {
        if (-not (b -c $i.FullName)) {
            Write-Host "Skipping file $($i.Name) because it's not a valid 3D print file."
            $g = $false
        }
    }
    return $g
}

$j = a
if ($j) {
    $k = Join-Path $networkFolder $today
    $l = Join-Path $j $today
    if (Test-Path $k) {
        Write-Host "Found folder $k. Checking contents..."
        if (Test-Path $l) {
            Write-Host "Destination folder $l already exists. Deleting..."
            Remove-Item -Path $l -Recurse -Force
            Write-Host "Old folder deleted."
        }
        Start-Sleep -s 5
        if (c -f $k) {
            Write-Host "Copying folder to USB drive..."
            Copy-Item -Path $k -Destination $l -Recurse -Force
            Write-Host "Folder copied successfully to $l."
        } else {
            Write-Host "Folder contains invalid files. Skipping copy."
        }
    } else {
        Write-Host "No folder found for today's date ($today) at $networkFolder."
    }
} else {
    Write-Host "USB drive with letter '$usbDriveLetter' not found."
}
start-Sleep -Seconds 20
}